"""add kyc_metadata and image_quality columns

Revision ID: 78783acfe21b
Revises: 
Create Date: 2026-05-21 18:37:39.148754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78783acfe21b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kyc_documents_s3_object_key', table_name='kyc_documents')
    op.drop_index('idx_kyc_documents_user_id', table_name='kyc_documents')
    op.drop_index('idx_kyc_documents_verification_status', table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.create_index(op.f('ix_alerts_kyc_session_id'), 'alerts', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_aml_screenings_kyc_session_id'), 'aml_screenings', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_aml_screenings_tenant_id'), 'aml_screenings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_kyc_session_id'), 'audit_logs', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cases_kyc_session_id'), 'cases', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_corporate_directors_kyc_session_id'), 'corporate_directors', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_corporate_directors_tenant_id'), 'corporate_directors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_corporate_profiles_kyc_session_id'), 'corporate_profiles', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_corporate_profiles_tenant_id'), 'corporate_profiles', ['tenant_id'], unique=False)
    op.alter_column('document_verifications', 'extracted_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_verifications', 'confidence_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_doc_verif_document_id', table_name='document_verifications')
    op.create_index(op.f('ix_document_verifications_document_id'), 'document_verifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_verifications_user_id'), 'document_verifications', ['user_id'], unique=False)
    op.drop_index('idx_documents_s3_key', table_name='documents')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_verification_status', table_name='documents')
    op.create_index(op.f('ix_documents_kyc_session_id'), 'documents', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_documents_onboarding_id'), 'documents', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.add_column('face_verifications', sa.Column('image_quality', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_face_verifications_kyc_session_id'), 'face_verifications', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_face_verifications_tenant_id'), 'face_verifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_individual_profiles_kyc_session_id'), 'individual_profiles', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_individual_profiles_tenant_id'), 'individual_profiles', ['tenant_id'], unique=False)
    op.drop_index('idx_kyc_sessions_active', table_name='kyc_sessions')
    op.drop_index('idx_kyc_sessions_tenant_id', table_name='kyc_sessions')
    op.drop_index('idx_kyc_sessions_user_id', table_name='kyc_sessions')
    op.drop_index('uq_kyc_step_states_session_step', table_name='kyc_step_states')
    op.add_column('onboarding_state', sa.Column('kyc_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_onboarding_state_kyc_session_id'), 'onboarding_state', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_onboarding_state_tenant_id'), 'onboarding_state', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_kyc_session_id'), 'risk_scores', ['kyc_session_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_tenant_id'), 'risk_scores', ['tenant_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('customer', 'kyc_officer', 'aml_analyst', 'compliance_manager', 'auditor', 'admin', name='user_role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::character varying"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_supabase_uid', table_name='users')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_supabase_uid_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_index('idx_workflow_events_status', table_name='workflow_events')
    op.drop_index('idx_workflow_events_tenant_created', table_name='workflow_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_workflow_events_tenant_created', 'workflow_events', ['tenant_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_workflow_events_status', 'workflow_events', ['event_status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_supabase_uid_key', 'users', ['supabase_uid'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_users_supabase_uid', 'users', ['supabase_uid'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'kyc_officer', 'aml_analyst', 'compliance_manager', 'auditor', 'admin', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::character varying"))
    op.drop_index(op.f('ix_risk_scores_tenant_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_kyc_session_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_onboarding_state_tenant_id'), table_name='onboarding_state')
    op.drop_index(op.f('ix_onboarding_state_kyc_session_id'), table_name='onboarding_state')
    op.drop_column('onboarding_state', 'kyc_metadata')
    op.create_index('uq_kyc_step_states_session_step', 'kyc_step_states', ['kyc_session_id', 'step_code'], unique=True)
    op.create_index('idx_kyc_sessions_user_id', 'kyc_sessions', ['user_id'], unique=False)
    op.create_index('idx_kyc_sessions_tenant_id', 'kyc_sessions', ['tenant_id'], unique=False)
    op.create_index('idx_kyc_sessions_active', 'kyc_sessions', ['user_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_individual_profiles_tenant_id'), table_name='individual_profiles')
    op.drop_index(op.f('ix_individual_profiles_kyc_session_id'), table_name='individual_profiles')
    op.drop_index(op.f('ix_face_verifications_tenant_id'), table_name='face_verifications')
    op.drop_index(op.f('ix_face_verifications_kyc_session_id'), table_name='face_verifications')
    op.drop_column('face_verifications', 'image_quality')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_onboarding_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_kyc_session_id'), table_name='documents')
    op.create_index('idx_documents_verification_status', 'documents', ['verification_status'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('idx_documents_s3_key', 'documents', ['s3_key'], unique=False)
    op.drop_index(op.f('ix_document_verifications_user_id'), table_name='document_verifications')
    op.drop_index(op.f('ix_document_verifications_document_id'), table_name='document_verifications')
    op.create_index('idx_doc_verif_document_id', 'document_verifications', ['document_id'], unique=False)
    op.alter_column('document_verifications', 'confidence_scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_verifications', 'extracted_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_corporate_profiles_tenant_id'), table_name='corporate_profiles')
    op.drop_index(op.f('ix_corporate_profiles_kyc_session_id'), table_name='corporate_profiles')
    op.drop_index(op.f('ix_corporate_directors_tenant_id'), table_name='corporate_directors')
    op.drop_index(op.f('ix_corporate_directors_kyc_session_id'), table_name='corporate_directors')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_kyc_session_id'), table_name='cases')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_kyc_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_aml_screenings_tenant_id'), table_name='aml_screenings')
    op.drop_index(op.f('ix_aml_screenings_kyc_session_id'), table_name='aml_screenings')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_kyc_session_id'), table_name='alerts')
    op.create_table('kyc_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('s3_object_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('s3_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('upload_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kyc_documents_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kyc_documents_pkey')
    )
    op.create_index('idx_kyc_documents_verification_status', 'kyc_documents', ['verification_status'], unique=False)
    op.create_index('idx_kyc_documents_user_id', 'kyc_documents', ['user_id'], unique=False)
    op.create_index('idx_kyc_documents_s3_object_key', 'kyc_documents', ['s3_object_key'], unique=False)
    # ### end Alembic commands ###
